<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="comp24" failures="0" tests="1" name="global.coda.hospital.operations.OperationsTest" time="25.596" errors="1" timestamp="2019-08-26T23:16:19 PDT" skipped="0">
  <testcase classname="global.coda.hospital.operations.OperationsTest" name="createIOTest" time="25.596">
    <error message="
Method OperationsTest.createIOTest()[pri:0, instance:global.coda.hospital.operations.OperationsTest@3bd40a57] should have thrown an exception of type class global.coda.hospital.exceptions.HospitalExceptions" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Method OperationsTest.createIOTest()[pri:0, instance:global.coda.hospital.operations.OperationsTest@3bd40a57] should have thrown an exception of type class global.coda.hospital.exceptions.HospitalExceptions
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:729)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:616)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- createIOTest -->
</testsuite> <!-- global.coda.hospital.operations.OperationsTest -->
